POST http://localhost:3003/api/blogs  HTTP/1.1
Content-Type: application/json

{
    "title": "Structure of backend application, introduction to testing",
    "author": "Full Stack Open",
    "url": "https://fullstackopen.com/en/part4/structure_of_backend_application_introduction_to_testing",
    "likes": 42
}
